version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  app:
    build: .
    ports:
      - "80:80"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=80
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev

  worker:
    build: .
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run worker

volumes:
  redis_data: